package club.doki7.vulkan.enumtype;

import club.doki7.ffm.annotation.*;

/// @see <a href="https://registry.khronos.org/vulkan/specs/latest/man/html/VkGpaPerfBlockAMD.html"><code>VkGpaPerfBlockAMD</code></a>
public final class VkGpaPerfBlockAMD {
    public static final int CPF = 0x0;
    public static final int IA = 0x1;
    public static final int VGT = 0x2;
    public static final int PA = 0x3;
    public static final int SC = 0x4;
    public static final int SPI = 0x5;
    public static final int SQ = 0x6;
    public static final int SX = 0x7;
    public static final int TA = 0x8;
    public static final int TD = 0x9;
    public static final int TCP = 0xa;
    public static final int TCC = 0xb;
    public static final int TCA = 0xc;
    public static final int DB = 0xd;
    public static final int CB = 0xe;
    public static final int GDS = 0xf;
    public static final int SRBM = 0x10;
    public static final int GRBM = 0x11;
    public static final int GRBM_SE = 0x12;
    public static final int RLC = 0x13;
    public static final int DMA = 0x14;
    public static final int MC = 0x15;
    public static final int CPG = 0x16;
    public static final int CPC = 0x17;
    public static final int WD = 0x18;
    public static final int TCS = 0x19;
    public static final int ATC = 0x1a;
    public static final int ATC_L2 = 0x1b;
    public static final int MC_VM_L2 = 0x1c;
    public static final int EA = 0x1d;
    public static final int RPB = 0x1e;
    public static final int RMI = 0x1f;
    public static final int UMCCH = 0x20;
    public static final int GE = 0x21;
    public static final int GL1A = 0x22;
    public static final int GL1C = 0x23;
    public static final int GL1CG = 0x24;
    public static final int GL2A = 0x25;
    public static final int GL2C = 0x26;
    public static final int CHA = 0x27;
    public static final int CHC = 0x28;
    public static final int CHCG = 0x29;
    public static final int GUS = 0x2a;
    public static final int GCR = 0x2b;
    public static final int PH = 0x2c;
    public static final int UTCL1 = 0x2d;
    public static final int GE_DIST = 0x2e;
    public static final int GE_SE = 0x2f;
    public static final int DF_MALL = 0x30;
    public static final int SQ_WGP = 0x31;
    public static final int PC = 0x32;
    public static final int GL1XA = 0x33;
    public static final int GL1XC = 0x34;
    public static final int WGS = 0x35;
    public static final int EACPWD = 0x36;
    public static final int EASE = 0x37;
    public static final int RLCUSER = 0x38;

    public static String explain(@EnumType(VkGpaPerfBlockAMD.class) int value) {
        return switch (value) {
            case VkGpaPerfBlockAMD.ATC -> "VK_GPA_PERF_BLOCK_ATC_AMD";
            case VkGpaPerfBlockAMD.ATC_L2 -> "VK_GPA_PERF_BLOCK_ATC_L2_AMD";
            case VkGpaPerfBlockAMD.CB -> "VK_GPA_PERF_BLOCK_CB_AMD";
            case VkGpaPerfBlockAMD.CHA -> "VK_GPA_PERF_BLOCK_CHA_AMD";
            case VkGpaPerfBlockAMD.CHCG -> "VK_GPA_PERF_BLOCK_CHCG_AMD";
            case VkGpaPerfBlockAMD.CHC -> "VK_GPA_PERF_BLOCK_CHC_AMD";
            case VkGpaPerfBlockAMD.CPC -> "VK_GPA_PERF_BLOCK_CPC_AMD";
            case VkGpaPerfBlockAMD.CPF -> "VK_GPA_PERF_BLOCK_CPF_AMD";
            case VkGpaPerfBlockAMD.CPG -> "VK_GPA_PERF_BLOCK_CPG_AMD";
            case VkGpaPerfBlockAMD.DB -> "VK_GPA_PERF_BLOCK_DB_AMD";
            case VkGpaPerfBlockAMD.DF_MALL -> "VK_GPA_PERF_BLOCK_DF_MALL_AMD";
            case VkGpaPerfBlockAMD.DMA -> "VK_GPA_PERF_BLOCK_DMA_AMD";
            case VkGpaPerfBlockAMD.EACPWD -> "VK_GPA_PERF_BLOCK_EACPWD_AMD";
            case VkGpaPerfBlockAMD.EASE -> "VK_GPA_PERF_BLOCK_EASE_AMD";
            case VkGpaPerfBlockAMD.EA -> "VK_GPA_PERF_BLOCK_EA_AMD";
            case VkGpaPerfBlockAMD.GCR -> "VK_GPA_PERF_BLOCK_GCR_AMD";
            case VkGpaPerfBlockAMD.GDS -> "VK_GPA_PERF_BLOCK_GDS_AMD";
            case VkGpaPerfBlockAMD.GE -> "VK_GPA_PERF_BLOCK_GE_AMD";
            case VkGpaPerfBlockAMD.GE_DIST -> "VK_GPA_PERF_BLOCK_GE_DIST_AMD";
            case VkGpaPerfBlockAMD.GE_SE -> "VK_GPA_PERF_BLOCK_GE_SE_AMD";
            case VkGpaPerfBlockAMD.GL1A -> "VK_GPA_PERF_BLOCK_GL1A_AMD";
            case VkGpaPerfBlockAMD.GL1CG -> "VK_GPA_PERF_BLOCK_GL1CG_AMD";
            case VkGpaPerfBlockAMD.GL1C -> "VK_GPA_PERF_BLOCK_GL1C_AMD";
            case VkGpaPerfBlockAMD.GL1XA -> "VK_GPA_PERF_BLOCK_GL1XA_AMD";
            case VkGpaPerfBlockAMD.GL1XC -> "VK_GPA_PERF_BLOCK_GL1XC_AMD";
            case VkGpaPerfBlockAMD.GL2A -> "VK_GPA_PERF_BLOCK_GL2A_AMD";
            case VkGpaPerfBlockAMD.GL2C -> "VK_GPA_PERF_BLOCK_GL2C_AMD";
            case VkGpaPerfBlockAMD.GRBM -> "VK_GPA_PERF_BLOCK_GRBM_AMD";
            case VkGpaPerfBlockAMD.GRBM_SE -> "VK_GPA_PERF_BLOCK_GRBM_SE_AMD";
            case VkGpaPerfBlockAMD.GUS -> "VK_GPA_PERF_BLOCK_GUS_AMD";
            case VkGpaPerfBlockAMD.IA -> "VK_GPA_PERF_BLOCK_IA_AMD";
            case VkGpaPerfBlockAMD.MC -> "VK_GPA_PERF_BLOCK_MC_AMD";
            case VkGpaPerfBlockAMD.MC_VM_L2 -> "VK_GPA_PERF_BLOCK_MC_VM_L2_AMD";
            case VkGpaPerfBlockAMD.PA -> "VK_GPA_PERF_BLOCK_PA_AMD";
            case VkGpaPerfBlockAMD.PC -> "VK_GPA_PERF_BLOCK_PC_AMD";
            case VkGpaPerfBlockAMD.PH -> "VK_GPA_PERF_BLOCK_PH_AMD";
            case VkGpaPerfBlockAMD.RLCUSER -> "VK_GPA_PERF_BLOCK_RLCUSER_AMD";
            case VkGpaPerfBlockAMD.RLC -> "VK_GPA_PERF_BLOCK_RLC_AMD";
            case VkGpaPerfBlockAMD.RMI -> "VK_GPA_PERF_BLOCK_RMI_AMD";
            case VkGpaPerfBlockAMD.RPB -> "VK_GPA_PERF_BLOCK_RPB_AMD";
            case VkGpaPerfBlockAMD.SC -> "VK_GPA_PERF_BLOCK_SC_AMD";
            case VkGpaPerfBlockAMD.SPI -> "VK_GPA_PERF_BLOCK_SPI_AMD";
            case VkGpaPerfBlockAMD.SQ -> "VK_GPA_PERF_BLOCK_SQ_AMD";
            case VkGpaPerfBlockAMD.SQ_WGP -> "VK_GPA_PERF_BLOCK_SQ_WGP_AMD";
            case VkGpaPerfBlockAMD.SRBM -> "VK_GPA_PERF_BLOCK_SRBM_AMD";
            case VkGpaPerfBlockAMD.SX -> "VK_GPA_PERF_BLOCK_SX_AMD";
            case VkGpaPerfBlockAMD.TA -> "VK_GPA_PERF_BLOCK_TA_AMD";
            case VkGpaPerfBlockAMD.TCA -> "VK_GPA_PERF_BLOCK_TCA_AMD";
            case VkGpaPerfBlockAMD.TCC -> "VK_GPA_PERF_BLOCK_TCC_AMD";
            case VkGpaPerfBlockAMD.TCP -> "VK_GPA_PERF_BLOCK_TCP_AMD";
            case VkGpaPerfBlockAMD.TCS -> "VK_GPA_PERF_BLOCK_TCS_AMD";
            case VkGpaPerfBlockAMD.TD -> "VK_GPA_PERF_BLOCK_TD_AMD";
            case VkGpaPerfBlockAMD.UMCCH -> "VK_GPA_PERF_BLOCK_UMCCH_AMD";
            case VkGpaPerfBlockAMD.UTCL1 -> "VK_GPA_PERF_BLOCK_UTCL1_AMD";
            case VkGpaPerfBlockAMD.VGT -> "VK_GPA_PERF_BLOCK_VGT_AMD";
            case VkGpaPerfBlockAMD.WD -> "VK_GPA_PERF_BLOCK_WD_AMD";
            case VkGpaPerfBlockAMD.WGS -> "VK_GPA_PERF_BLOCK_WGS_AMD";
            default -> "UNKNOWN(" + value + ")";
        };
    }

    /// Constructing this class is nonsense so the constructor is made private.
    private VkGpaPerfBlockAMD() {}
}
